import { createMuiTheme } from "@material-ui/core/styles";
import { 
  AppBarStyles,
  AvatarStyles,
  BackdropStyles,
  BadgeStyles,
  BottomNavigationStyles,
  BottomNavigationActionStyles,
  BreadcrumbsStyles,
  ButtonStyles,
  ButtonBaseStyles,
  TouchRippleStyles,
  ButtonGroupStyles,
  CardStyles,
  CardActionAreaStyles,
  CardActionsStyle,
  CardContentStyles,
  CardHeaderStyles,
  CardMediaStyles,
  CheckboxStyles,
  ChipStyles,
  CircularProgressStyles,
  CollapseStyles,
  ContainerStyles,
  DialogStyles,
  DialogActionsStyles,
  DialogContentStyles,
  DialogContentTextStyles,
  DialogTitleStyles,
  DividerStyles,
  DrawerStyles,
  ExpansionPanelStyles,
  ExpansionPanelActionsStyles,
  ExpansionPanelDetailsStyles,
  ExpansionPanelSummaryStyles,
  FabStyles,
  FilledInputStyles,
  FormControlStyles,
  FormControlLabelStyles,
  FormGroupStyles,
  FormHelperTextStyles,
  FormLabelStyles,
  GridListStyles,
  GridListTileStyles,
  GridListTileBarStyles,
  IconStyles,
  IconButtonStyles,
  InputStyles,
  InputAdornmentStyles,
  InputBaseStyles,
  InputLabelStyles,
  LinearProgressStyles,
  LinkStyles,
  ListStyles,
  ListItemStyles,
  ListItemAvatarStyles,
  ListItemIconStyles,
  ListItemSecondaryActionStyles,
  ListItemTextStyles,
  ListSubheaderStyles,
  MenuStyles,
  MenuItemStyles,
  MobileStepperStyles,
  ModalStyles,
  NativeSelectStyles,
  OutlinedInputStyles,
  PaperStyles,
  PopoverStyles,
  RadioStyles,
  SliderStyles,
  SnackbarStyles,
  SnackbarContentStyles,
  StepStyles,
  StepButtonStyles,
  StepConnectorStyles,
  StepContentStyles,
  StepIconStyles,
  StepLabelStyles,
  StepperStyles,
  SvgIconStyles,
  SwitchStyles,
  TabStyles,
  TableStyles,
  TableBodyStyles,
  TableCellStyles,
  TableContainerStyles,
  TableFooterStyles,
  TableHeadStyles,
  TablePaginationStyles,
  TableRowStyles,
  TableSortLabelStyles,
  TabsStyles,
  TextFieldStyles,
  ToolbarStyles,
  TooltipStyles,
  TypographyStyles,
} from "../customStyles";
import theme from "./themes";

theme.overrides = {
  MuiAppBar: AppBarStyles,
  MuiAvatar: AvatarStyles,
  MuiBackdrop: BackdropStyles,
  MuiBadge: BadgeStyles,
  MuiBottomNavigation: BottomNavigationStyles,
  MuiBottomNavigationAction: BottomNavigationActionStyles,
  MuiBreadcrumbs: BreadcrumbsStyles,
  MuiButton: ButtonStyles,
  MuiButtonBase: ButtonBaseStyles,
  MuiTouchRipple: TouchRippleStyles,
  MuiButtonGroup: ButtonGroupStyles,
  MuiCard: CardStyles,
  MuiCardActionArea: CardActionAreaStyles,
  MuiCardActions: CardActionsStyle,
  MuiCardContent: CardContentStyles,
  MuiCardHeader: CardHeaderStyles,
  MuiCardMedia: CardMediaStyles,
  MuiCheckbox: CheckboxStyles,
  MuiChip: ChipStyles,
  MuiCircularProgress: CircularProgressStyles,
  MuiCollapse: CollapseStyles,
  MuiContainer: ContainerStyles,
  MuiDialog: DialogStyles,
  MuiDialogActions: DialogActionsStyles,
  MuiDialogContent: DialogContentStyles,
  MuiDialogContentText: DialogContentTextStyles,
  MuiDialogTitle: DialogTitleStyles,
  MuiDivider: DividerStyles,
  MuiDrawer: DrawerStyles,
  MuiExpansionPanel: ExpansionPanelStyles,
  MuiExpansionPanelActions: ExpansionPanelActionsStyles,
  MuiExpansionPanelDetails: ExpansionPanelDetailsStyles,
  MuiExpansionPanelSummary: ExpansionPanelSummaryStyles,
  MuiFab: FabStyles,
  MuiFilledInput: FilledInputStyles,
  MuiFormControl: FormControlStyles,
  MuiFormControlLabel: FormControlLabelStyles,
  MuiFormGroup: FormGroupStyles,
  MuiFormHelperText: FormHelperTextStyles,
  MuiFormLabel: FormLabelStyles,
  MuiGridList: GridListStyles,
  MuiGridListTile: GridListTileStyles,
  MuiGridListTileBar: GridListTileBarStyles,
  MuiIcon: IconStyles,
  MuiIconButton: IconButtonStyles,
  MuiInput: InputStyles,
  MuiInputAdornment: InputAdornmentStyles,
  MuiInputBase: InputBaseStyles,
  MuiInputLabel: InputLabelStyles,
  MuiLinearProgress: LinearProgressStyles,
  MuiLink: LinkStyles,
  MuiList: ListStyles,
  MuiListItem: ListItemStyles,
  MuiListItemAvatar: ListItemAvatarStyles,
  MuiListItemIcon: ListItemIconStyles,
  MuiListItemSecondaryAction: ListItemSecondaryActionStyles,
  MuiListItemText: ListItemTextStyles,
  MuiListSubheader: ListSubheaderStyles,
  MuiMenu: MenuStyles,
  MuiMenuItem: MenuItemStyles,
  MuiMobileStepper: MobileStepperStyles,
  MuiModal: ModalStyles,
  MuiNativeSelect: NativeSelectStyles,
  MuiOutlinedInput: OutlinedInputStyles,
  MuiPaper: PaperStyles,
  MuiPopover: PopoverStyles,
  MuiRadio: RadioStyles,
  MuiSlider: SliderStyles,
  MuiSnackbar: SnackbarStyles,
  MuiSnackbarContent: SnackbarContentStyles,
  MuiStep: StepStyles,
  MuiStepButton: StepButtonStyles,
  MuiStepConnector: StepConnectorStyles,
  MuiStepContent: StepContentStyles,
  MuiStepIcon: StepIconStyles,
  MuiStepLabel: StepLabelStyles,
  MuiStepper: StepperStyles,
  MuiSvgIcon: SvgIconStyles,
  MuiSwitch: SwitchStyles,
  MuiTab: TabStyles,
  MuiTable: TableStyles,
  MuiTableBody: TableBodyStyles,
  MuiTableCell: TableCellStyles,
  MuiTableContainer: TableContainerStyles,
  MuiTableFooter: TableFooterStyles,
  MuiTableHead: TableHeadStyles,
  MuiTablePagination: TablePaginationStyles,
  MuiTableRow: TableRowStyles,
  MuiTableSortLabel: TableSortLabelStyles,
  MuiTabs: TabsStyles,
  MuiTextField: TextFieldStyles,
  MuiToolbar: ToolbarStyles,
  MuiTooltip: TooltipStyles,
  MuiTypography: TypographyStyles,
};

const customTheme = createMuiTheme(theme);

export default customTheme;
